import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from '@/components/globals/custom-cursor'
import RetroHeader from '@/components/globals/retro-header'
import Sidebar from '@/components/globals/sidebar'
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
        <CustomCursor />
        <div className="layout-container">
          <div className="sticky-header">
            <RetroHeader />
          </div>
          <div className="flex h-full">
            <Sidebar />
            <div className="content-container flex-grow   md:ml-64 ml-0">
              {children}
            </div>
          </div>
        </div>
        </SessionProvider>
      </body>
    </html>
  )
}